server:
  port: 8080

spring:
  application:
    name: cv-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # Use "update" for development, but "validate" for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: adminpassword

logging:
  level:
    org:
      springframework: INFO

allowed:
  origins: http://localhost:4200

llm:
  api:
    google:
      key: ${GOOGLE_API_KEY}
      model: gemini-2.0-flash-001
