server:
  port: 8080

spring:
  application:
    name: cv-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/externals-db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate   # Use "update" for development, but "validate" for production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  docker:
    compose:
      enabled: false

logging:
  level:
    org:
      springframework: INFO

allowed:
  origins: http://localhost:4200

app:
  mock:
    flag: false
  ai:
    server:
      url: http://localhost:8080
