server:
  port: 8080

spring:
  application:
    name: cv-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/externals-db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  docker:
    compose:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: adminpassword
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/migration/V1__Create_user_and_candidate_tables.sql
        - classpath:db/migration/V2__Offers__and__interviews__tables.sql
      data-locations: classpath:db/insertion/Data.sql
      continue-on-error: false

  mail:
    host: smtp.yourprovider.com   # e.g. smtp.gmail.com
    port: 587
    username: your_user
    password: your_pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework: INFO

allowed:
  origins: http://localhost:4200

app:
  mock:
    flag: true
  ai:
    server:
      url: http://localhost:8080
  mail:
    from: no-reply@your-domain.com
  tts:
    apiKey: sk_85057635cdb9f1c0f62bc9eec572268ed6ba80ffc4702cda
    modelId: eleven_multilingual_v2
    voiceId: 21m00Tcm4TlvDq8ikWAM
    stability: 0.5
    similarityBoost: 0.5
    style: 0.0
    useSpeakerBoost: true
    speed: 1.0

interview:
  token:
    expirationMillis: 86400000
    secret: OWSJytPLVnDkgwLd7NbZKaxIA63VOE+R8suNr8n7bIqvGzUvHTZLOlqX4x6fBmw6udTuBENk6plQwY+fg/5ZGw==
  email:
    template:
      path: templates/interviewsInvitation.html
  baseLink: http://localhost:4200/interviews/
