server:
  port: 8080

spring:
  application:
    name: cv-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/externals-db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  docker:
    compose:
      enabled: false
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: adminpassword
  sql:
    init:
      mode: always
      schema-locations:
      - classpath:db/migration/V1__Create_user_and_candidate_tables.sql
      - classpath:db/migration/V2__Offers__and__interviews__tables.sql
      data-locations: classpath:db/insertion/Data.sql
      continue-on-error: false
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: mohamedtaha.elyakoubi@nttdata.com
    password: dT5A6H5A6@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework: INFO

allowed:
  origins: http://localhost:4200

app:
  mock:
    flag: true
  ai:
    server:
      url: http://localhost:8080
  mail:
    from: mohamedtaha.elyakoubi@nttdata.com

interview:
  token:
    expirationMillis: 86400000
    secret: OWSJytPLVnDkgwLd7NbZKaxIA63VOE+R8suNr8n7bIqvGzUvHTZLOlqX4x6fBmw6udTuBENk6plQwY+fg/5ZGw==
  email:
    template:
      path: templates/interviewsInvitation.html