server:
  port: 8080

spring:
  application:
    name: cv-management-system
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: local

logging:
  level:
    org:
      springframework: INFO

