name: Maven Build and Test

on:
  push:
    branches:
      - main
      - develop
      - uat
  pull_request:
    branches:
      - main
      - develop
      - uat

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean install -DskipTests=true # skip tests during build
      - name: Run Tests with Maven
        run: mvn test